Second batch of agreed risk scores added
Nathan-Philippo/risk-engine-rules pull request #5
Opened 2018-06-12 10:10 UTC by SeanSuckling

Second batch of risk scores for business type added - scores as agreed at team workshop.

2018-06-14 13:24 UTC, Nathan-Philippo requested changes
Sean, we seem to have lost the names of quite a few of the business types, was this intentional? if not they will need to be re added before we can approve

2018-06-14 13:49 UTC, SeanSuckling commented
I can't see any missing business types, can you give an example? Some of the formatting is out re the answers to the business type questions which might be giving the impression that business types are missing.

2018-06-14 14:15 UTC, Nathan-Philippo commented on business-types.json
>      "baseScores": {
Sean - no business type on this one, can see the changes to the scores but i cannot determine the business type

2018-06-14 14:16 UTC, Nathan-Philippo commented
Sean,

So line 186 to 194, there is no name business type, only the scores that you have changed.

I have tried leaving a comment of the got hub file, can you see it?

regards

Nathan Philippo
Regulating Our Future Programme
Food Standards Agency
02072768372
07775032157
www.food.gov.uk<http://www.food.gov.uk>

From: SeanSuckling [mailto:notifications@github.com]
Sent: 14 June 2018 14:49
To: Nathan-Philippo/risk-engine-rules <risk-engine-rules@noreply.github.com>
Cc: Nathan Philippo <Nathan.Philippo@food.gov.uk>; Review requested <review_requested@noreply.github.com>
Subject: Re: [Nathan-Philippo/risk-engine-rules] Second batch of agreed risk scores added (#5)


I can't see any missing business types, can you give an example? Some of the formatting is out re the answers to the business type questions which might be giving the impression that business types are missing.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/Nathan-Philippo/risk-engine-rules/pull/5#issuecomment-397302418>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlslxA85qRwbWEV6iSpHhOky7rS2opQCks5t8mnSgaJpZM4UkJhJ>.

Food Standards Agency (FSA) For the latest food news and information visit www.food.gov.uk This email and any attachments are intended for the named recipient only. Unauthorised use, disclosure, storage or copying is not permitted. If you have received this email in error, please destroy all copies and inform the sender immediately by return email. The original of this email was scanned for viruses by the Government Secure Intranet (GSI) virus scanning service supplied exclusively by Cable & Wireless Worldwide in partnership with MessageLabs and on leaving the GSI this email was certified virus-free. However you should always use your own virus-scanning software to ensure mail and attachments are safe to open. Communications on the FSA's computer systems may be monitored and/or recorded to secure effective operation of the system and for other lawful purposes.

2018-06-25 16:54 UTC, Nathan-Philippo requested changes
76: remove the new H - **DONE**
190: why is depuration not give 20 for MOP - **20 ADDED** 
271: Is milk pasteurised, if not its fine - **LEAVE AS 20 - PRECUATIONARY PRINCIPLE**
378: does not handle food - **AGREE, CHANGED TO 5** 
407: does not handle food - **AGREE, CHANGED TO 5**
445: can i see definition - **MEETING ARRANGED TO REVIEW DEFINITIONS**
479: can i see definition - **MEETING ARRANGED TO REVIEW DEFINITIONS**
638: why handling score of 10? - **OPINION IS THAT MOST NEWSAGENTS/POST OFFICES NOW RETAIL PRE-PACKED HIGH RISK FOODS THAT REQUIRE TEMPERATURE CONTROL (EG SANDWICHES, DAIRY ETC)**
839: why only 5 for consumers at risk if fast for restaurant is a 10? - **FAST FOOD RESTAURANT (736) WRONG, CHANGED TO 5**
916: MOP cannot be a 5. - **SCORE FOR VULNERABLE GROUPS ENTERED ON WRONG LINE. 916 CORRECTED TO 0, LINE 917 CHANGED FROM 0 TO 5**

2018-06-28 08:02 UTC, SeanSuckling commented
See comments above. I will commit the amendments.

2018-07-02 15:34 UTC, Nathan-Philippo approved these changes

2018-07-02 15:36 UTC, Nathan-Philippo commented
Sean, approved but once we have discussed the definition of some business types we may need to revisit 445 and 479

2018-07-03 08:43 UTC, SeanSuckling commented
Agree, thanks

Sean

From: Nathan-Philippo [mailto:notifications@github.com]
Sent: 02 July 2018 16:36
To: Nathan-Philippo/risk-engine-rules <risk-engine-rules@noreply.github.com>
Cc: Suckling, Sean <Sean.Suckling@food.gov.uk>; Author <author@noreply.github.com>
Subject: Re: [Nathan-Philippo/risk-engine-rules] Second batch of agreed risk scores added (#5)


Sean, approved but once we have discussed the definition of some business types we may need to revisit 445 and 479

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Nathan-Philippo/risk-engine-rules/pull/5#issuecomment-401845562>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Alsl2HlEUo15ur6WWHG1HKhOS_LhsxLnks5uCj3vgaJpZM4UkJhJ>.

Food Standards Agency (FSA) For the latest food news and information visit www.food.gov.uk This email and any attachments are intended for the named recipient only. Unauthorised use, disclosure, storage or copying is not permitted. If you have received this email in error, please destroy all copies and inform the sender immediately by return email. The original of this email was scanned for viruses by the Government Secure Intranet (GSI) virus scanning service supplied exclusively by Cable & Wireless Worldwide in partnership with MessageLabs and on leaving the GSI this email was certified virus-free. However you should always use your own virus-scanning software to ensure mail and attachments are safe to open. Communications on the FSA's computer systems may be monitored and/or recorded to secure effective operation of the system and for other lawful purposes.

2018-07-25 15:20 UTC, merged